### ISSUE TITLE
npm run-script assets fails

### ISSUE THREAD

**Issue by ddpkts** [ongr-io/Demo#151]
JFYI, failed installing Demo project.

[Step 6: Install the demo data](https://github.com/ongr-io/Demo/blob/master/src/ONGR/DemoBundle/Resources/doc/index.rst#step-6-install-the-demo-data)

```
vagrant@ongr:/var/www$ npm run-script assets

> ongr-sandbox@0.0.0 assets /var/www
> gulp && app/console assetic:dump


module.js:340
    throw err;
    ^
Error: Cannot find module 'gulp-sass'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/Gulpfile.js:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! ongr-sandbox@0.0.0 assets: `gulp && app/console assetic:dump`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the ongr-sandbox@0.0.0 assets script.
npm ERR! This is most likely a problem with the ongr-sandbox package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp && app/console assetic:dump
npm ERR! You can get their info via:
npm ERR!     npm owner ls ongr-sandbox
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-35-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "run-script" "assets"
npm ERR! cwd /var/www
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/npm-debug.log
npm ERR! not ok code 0
```

/var/www/npm-debug.log

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run-script', 'assets' ]
2 info using npm@1.4.28
3 info using node@v0.10.40
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'preassets', 'assets', 'postassets' ]
6 info preassets ongr-sandbox@0.0.0
7 info assets ongr-sandbox@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info ongr-sandbox@0.0.0 Failed to exec assets script
10 error ongr-sandbox@0.0.0 assets: `gulp && app/console assetic:dump`
10 error Exit status 8
11 error Failed at the ongr-sandbox@0.0.0 assets script.
11 error This is most likely a problem with the ongr-sandbox package,
11 error not with npm itself.
11 error Tell the author that this fails on your system:
11 error     gulp && app/console assetic:dump
11 error You can get their info via:
11 error     npm owner ls ongr-sandbox
11 error There is likely additional logging output above.
12 error System Linux 3.13.0-35-generic
13 error command "/usr/bin/node" "/usr/bin/npm" "run-script" "assets"
14 error cwd /var/www
15 error node -v v0.10.40
16 error npm -v 1.4.28
17 error code ELIFECYCLE
18 verbose exit [ 1, true ]
```

**Comment by saimaz** [comment]
Some people reporting that this is because of `gulp-sass`. Can you please rebuild that component with npm?

`npm rebuild gulp-sass`?

**Comment by ddpkts** [comment]
`npm install` worked

**Comment by saimaz** [comment]
nice. 

I'm gonna keep this issue as a holder for docs check when it will be fixed.

**Comment by saimaz** [comment]
for the proggress check: #152
